---
- name: Create omada user
  ansible.builtin.user:
    name: omada
    comment: 'omada service account'
    system: true
    shell: /usr/sbin/nologin
    home: /opt/tplink/EAPController/data
    state: present

- name: Stop omada service
  ansible.builtin.command: tpeap stop
  register: tpeap_status
  changed_when: tpeap_status.rc != 0

- name: Modify 'control.sh', change default 'OMADA_USER'
  ansible.builtin.lineinfile:
    path: /opt/tplink/EAPController/bin/control.sh
    search_string: 'OMADA_USER=${OMADA_USER:-root}'
    line: OMADA_USER=${OMADA_USER:-omada}

- name: Modify 'control.sh', change 'PID_FILE' path
  ansible.builtin.lineinfile:
    path: /opt/tplink/EAPController/bin/control.sh
    search_string: 'PID_FILE="/var/run/${NAME}.pid"'
    line: 'PID_FILE="${OMADA_HOME}/data/${NAME}.pid"'

- name: Modify 'control.sh', remove 'check_root_perms' func call
  ansible.builtin.lineinfile:
    path: /opt/tplink/EAPController/bin/control.sh
    search_string: 'check_root_perms'
    line: '#check_root_perms'

- name: Change omada directories to non-root owner & group
  ansible.builtin.file:
    path: '{{ omada_dir }}'
    state: directory
    recurse: true
    owner: omada
    group: omada
  loop:
    - /opt/tplink/EAPController/data
    - /opt/tplink/EAPController/logs
    - /opt/tplink/EAPController/work
  loop_control:
    loop_var: omada_dir
